os: "windows"
language: "c"

env:
  global:
    - 'CABOPTS="--store-dir=C:\\SR --http-transport=plain-http" CHOCOPTS=""'

  matrix:
    include:
    # 64 bit builds
    - env: GHCVER=8.4.2 CABALVER=2.4.1.0
    - env: GHCVER=8.0.2 CABALVER=2.4.1.0

before_install:
 - choco install -y ghc --version "$GHCVER" "$CHOCOPTS"
 - choco install -y cabal --version "$CABALVER" "$CHOCOPTS"
 - choco install -y 7zip
 - choco install -y curl
 - curl -O https://download.libsodium.org/libsodium/releases/libsodium-1.0.16-msvc.zip
 - 7z x libsodium-1.0.16-msvc.zip -oc:\\WORK\\sodium
 - dir c:\\WORK\\sodium
 - cabal --version
 - ghc --version
 - cabal "$CABOPTS" new-update -vverbose+nowrap

install:
 - set LIBRARY_PATH=c:\\WORK\\sodium\\x64\\Release\\v141\\dynamic
 - cabal "$CABOPTS" new-build --extra-include-dirs c:\\WORK\\sodium\\include  --extra-lib-dirs c:\\WORK\\sodium\\x64\\Release\\v141\\dynamic -j1 all

script: []
