* Things to be done
** Create a basic client like hocus-pocus in the library repository. (DONE)
** make it work for text messages via custom input codes. (DONE)
** PGP word list support. (DONE)
** command completion for code input. (DONE)
** reorganize the modules to have a file/dir transfer library on top of the wormhole library. (DONE)
** handle ack message that the receiver of a file/dir transfer sends to the sender. (DONE)
   The ack message is of this form: {"ack": "ok", "sha256": "e4f1684a5375ebf7f1dcde02a66026f937a8c6195adf31813ef21b3ccadfb11f"}

** Tests (hedgehog round trip tests for json messages) (DONE)
** support for transit protocol for files.
*** direct tcp connection
**** Send (DONE)
**** Receive
*** via relay
**** Send
**** Receive
** Setup CI system
** Integration tests with python app.
** Try to optimize the wordlist completion in receive (256*2 entry table instead of 256*256 entries)
** support for directory transfers via transit protocol.
** error handling at the moment is terrible. This needs to be thought through and fixed.
** review the exposed functions from wormhole library and see if they strictly need to be exposed.
